import 'package:flutter/material.dart';

void main() {
  runApp(const OldFlareToRiveApp());
}

class OldFlareToRiveApp extends StatelessWidget {
  const OldFlareToRiveApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: MigrationDemoPage(),
    );
  }
}

class MigrationDemoPage extends StatefulWidget {
  const MigrationDemoPage({super.key});

  @override
  State<MigrationDemoPage> createState() => _MigrationDemoPageState();
}

class _MigrationDemoPageState extends State<MigrationDemoPage> {
  bool useRive = true;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Old Flare -> Rive Demo')),
      body: Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Text(
              useRive
                  ? 'Using Rive output generated by rive_cli + RML'
                  : 'Legacy Flare animation (for comparison)',
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: 16),
            SwitchListTile(
              title: const Text('Use Rive'),
              value: useRive,
              onChanged: (value) {
                setState(() {
                  useRive = value;
                });
              },
            ),
          ],
        ),
      ),
    );
  }
}
